
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: CodeScanCloudPrepare@1
  inputs:
    CodeScanCloud: 'CodeSCan US'
    organization: 'yana'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'new'
    cliProjectName: 'new'
    cliSources: '.'
    extraProperties: 'sonar.qualitygate.wait=true'
- task: CodeScanCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
- task: CodeScanCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: |
#       $token = [System.Text.Encoding]::UTF8.GetBytes(${env:CODESCAN_TOKEN} + ":")
#        $base64 = [System.Convert]::ToBase64String($token)
#        $basicAuth = [string]::Format("Basic {0}", $base64)
#        $headers = @{ Authorization = $basicAuth }
       
#        Write-Host "Pull Request ID:$($env:SYSTEM_PULLREQUEST_PULLREQUESTID)"
       
#        $Target = "$env:SYSTEM_PULLREQUEST_PULLREQUESTID"
#        $URL = "https://app.codescan.io/api/qualitygates/project_status?projectKey=new&pullRequest={0}"
       
#        if( !$Target)
#        {
#          $Target = "$env:BUILD_SOURCEBRANCH"
#          $Target = $Target.Replace('refs/heads/','')
#          Write-Host "$Target"
#          $URL = "https://app.codescan.io/api/qualitygates/project_status?projectKey=new&branch={0}"
#        } 
       
#        $URL = [string]::Format($URL, $Target)
#        Write-Host "$URL"
       
#        $result = Invoke-RestMethod -Method Get -Uri $URL  -Headers $headers
#        $result | ConvertTo-Json | Write-Host
        
#        if ($result.projectStatus.status -eq "OK") {
#        Write-Host "Quality Gate Succeeded"
#        }else{
#        throw "Quality Gate failed"
#        }

